version: "3"
services:
  database:
    image: 'postgres:15.2'
    container_name: it-offers-postgresql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database_volume:/var/lib/postgresql
    env_file: ".env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  mongodb:
    image: mongo:latest
    restart: always
    container_name: it-offers-mongodb
    hostname: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: it-offers

volumes:
  database_volume: {}