version: "3"
services:
  database:
    image: 'postgres:15.2'
    container_name: it-offers-postgresql
    ports:
      - "5432:5432"
    volumes:
      - database_volume:/var/lib/postgresql
    env_file: ".env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  database_volume: {}