spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
logging:
  level:
    org:
      springframework:
        security: DEBUG