spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 12
      max-lifetime: 1200000
      auto-commit: true
      minimum-idle: 5
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    password: ${POSTGRES_PASSWORD}
    user: ${POSTGRES_USER}
    baseline-description: "init"
    baseline-version: 0
jwt:
  token:
    secret: ${JWT_SECRET}
    lifetime: 60