spring:
  data:
    mongodb:
      uri: "${MONGO_DB_URI}/it-offers-integration-tests"
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        security: DEBUG