spring:
  data:
    mongodb:
      uri: "${MONGO_DB_URI}/it-offers-integration-tests"
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
logging:
  level:
    org:
      springframework:
        security: DEBUG