spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/it-offers
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
logging:
  level:
    org:
      springframework:
        security: DEBUG