name: it-offers ci/cd
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: '6.0'
        mongodb-replica-set: test-rs
        mongodb-username: admin
        mongodb-password: admin
        mongodb-db: it-offers-integration-tests

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and test with Maven
      run: mvn clean install
      env:
        JWT_SECRET: 2D4A614E645267556B58703273357638792F423F4428472B4B6250655368566D
        MONGODB_URI: mongodb://localhost:27017/it-offers-integration-tests
